#create database cinema;
#create table Employee(ID int primary key auto_increment , Employee_Name varchar(30) not null , Age int , Salary double , Phone varchar(20) ,  Department varchar(20));
#create table movie(Movie_ID int primary key auto_increment, Movie_Name varchar(30), Category varchar(30), Movie_Date varchar(30), Price varchar(20));
#insert into employee(employee.employee_name, employee.age, employee.Salary, employee.phone , employee.Department) values('Malak Ahamed', 20, 20000 ,'+201134879520', 'Supervisor'),( 'Malak Yasser', 19, 25000 ,'+201176984592', 'Manager'), ('Mariam Mohammed', 19, 10000,'+201026480376', 'HR'), ('Malak Sameh', 18, 10000 ,'+201248687659', 'Software Engineer'),('Menna Ehab', 19, 15000 ,'+201065489365', 'Leader'),('Malak Ayman', 20, 5000 ,'+201148765893', 'Seller'); 
#insert into movie(Movie_Name, Movie_Date, Price) values("Frozen", "1/1/2025", "20$");
#delete from movie where Movie_ID = 2;
#insert into movie(Movie_Name, Movie_Date, Price) values("Luca", "8/2/2025", "30$");
#insert into movie(Movie_Name, Movie_Date, Price) values("Raya", "4/1/2025", "26$");
#insert into movie(Movie_Name, Movie_Date, Price) values("Elemental", "3/2/2025", "30$");
#delete from movie where Movie_ID = 5;
#delete from movie where Movie_ID = 6;
#delete from movie where Movie_ID = 7;
#insert into movie(Movie_ID, Movie_Name, Movie_Date, Price) values(5,"Elemental", "3/2/2025", "30$");
#insert into movie(Movie_Name, Movie_Date, Price) values("Tangled", "9/2/2025", "50$");
#delete from movie where Movie_ID = 8;
#insert into movie(Movie_ID, Movie_Name, Movie_Date, Price) values(6, "Tangled", "9/2/2025", "50$");
#update movie set Category = "Cartoon" where Movie_ID = 1;
-- update movie set Category = "Cartoon" where Movie_ID = 3;
-- update movie set Category = "Cartoon" where Movie_ID = 4;
-- update movie set Category = "Cartoon" where Movie_ID = 5;
-- update movie set Category = "Cartoon" where Movie_ID = 6;
#drop table movie;
#create table movie( Movie_Name varchar(30), Movie_ID int primary key auto_increment, Category varchar(30), Movie_Date varchar(30), Price varchar(20));
#insert into movie(Movie_Name, Category ,Movie_Date, Price) values("Frozen", "Cartoon" , "1/1/2025", "20$");
#insert into movie(Movie_Name, Category ,Movie_Date, Price) values("Elemental", "Cartoon" ,"3/2/2025", "30$");
-- insert into movie(Movie_Name, Category ,Movie_Date, Price) values("Maleficent", "Fantasy", "19/2/2025", "66$");
-- insert into movie(Movie_Name, Movie_ID ,Category ,Movie_Date, Price) values("Titanic", 4,"Romantic", "29/1/2025", "88$");
#insert into movie(Movie_Name,Movie_ID, Category ,Movie_Date, Price) values("Maze Runner",5, "Action", "10/4/2025", "30$");
#insert into movie(Movie_Name, Movie_ID, Category ,Movie_Date, Price) values("BFG",6, "Fantasy", "9/2/2025", "50$");
-- insert into movie(Movie_Name, Movie_ID, Category ,Movie_Date, Price) values("BFG",6, "Fantasy", "9/2/2025", "50$");
-- insert into movie(Movie_Name,Movie_ID, Category ,Movie_Date, Price) values("Maze Runner",5, "Action", "10/4/2025", "30$");
select * from employee;
-- select * from movie;

